### ISSUE TITLE
Change links to GitLab

### ISSUE THREAD

**Issue by beenje** [conda-forge/taurus_pyqtgraph-feedstock#5]
Next time there is a new version, we should take the opportunity to update the home and dev_url links in `meta.yaml` to point to GitLab instead of GitHub.

Creating this issue as a reminder :-)

**Comment by cpascual** [comment]
Oops!
You are 100% right.

Can we just change them without witing for a new version? (I mention it because I also enabled automerge in #4, and I guess that means that the next version will be merged without intervention...)

**Comment by cpascual** [comment]
I'll make a PR for that
